/**
 * Marketing / product-page illustration tokens.
 * All values are CSS variable references — safe for inline styles and SVG attributes.
 */
export const mkt = {
  background: 'var(--background)',
  foreground: 'var(--foreground)',
  muted: 'var(--muted)',
  mutedForeground: 'var(--muted-foreground)',
  border: 'var(--border)',
  card: 'var(--card)',
  primary: 'var(--primary)',
  primaryHover: 'var(--primary-hover)',
  primaryForeground: 'var(--primary-foreground)',
  destructive: 'var(--destructive)',
  accent: 'var(--accent)',

  /** Collapsed nav rail in product mock SVGs */
  nav: 'var(--illustration-nav)',
  /** Headings in mobile product pages */
  ink: 'var(--illustration-ink)',
  inkSoft: 'var(--illustration-ink-soft)',
  line: 'var(--illustration-line)',
  success: 'var(--illustration-success)',
  successLight: 'var(--illustration-success-light)',
  warning: 'var(--illustration-warning)',
  info: 'var(--illustration-info)',
  infoLight: 'var(--illustration-info-light)',

  primaryTint: 'var(--illustration-primary-tint)',
  primaryTintBorder: 'var(--illustration-primary-tint-border)',
  successTint: 'var(--illustration-success-tint)',
  successTintBorder: 'var(--illustration-success-tint-border)',
  panel: 'var(--illustration-panel)',
  panelAlt: 'var(--illustration-panel-alt)',

  lensMid: 'var(--illustration-lens-mid)',
  lensDeep: 'var(--illustration-lens-deep)',
  lensDark: 'var(--illustration-lens-dark)',
  lensHighlight: 'var(--illustration-lens-highlight)',
  lensGlow: 'var(--illustration-lens-glow)',

  windowDotClose: 'var(--window-dot-close)',
  windowDotMinimize: 'var(--window-dot-minimize)',
  windowDotMaximize: 'var(--window-dot-maximize)',

  /** color-mix helpers for card themes */
  primaryDim: 'var(--illustration-primary-dim)',
  primaryBorder: 'var(--illustration-primary-border)',
  primaryRing: 'var(--illustration-primary-ring)',
  frameBg: 'var(--illustration-frame-bg)',
  frameBorder: 'var(--illustration-frame-border)',
  floatChipBg: 'var(--illustration-float-chip-bg)',
  floatChipBorder: 'var(--illustration-float-chip-border)',
  floatChipText: 'var(--illustration-float-chip-text)',
  titleColor: 'var(--foreground)',
  descColor: 'var(--illustration-desc-color)',
  benefitColor: 'var(--illustration-benefit-color)',
} as const

/** Shared SVG mock UI tokens (800×480 product screenshots). */
export const svgMock: Record<string, string> = {
  NAV: mkt.nav,
  W: mkt.background,
  BD: mkt.border,
  H: mkt.foreground,
  M: mkt.mutedForeground,
  PRM: mkt.primary,
  POS: mkt.success,
  WARN: mkt.warning,
  NEG: mkt.destructive,
  PANEL: mkt.panel,
  PANEL_ALT: mkt.panelAlt,
  INFO_BG: mkt.infoLight,
  SUCCESS_BG: mkt.successTint,
  INFO_BORDER: mkt.primaryTintBorder,
  SUCCESS_BORDER: mkt.successTintBorder,
  INFO: mkt.info,
  ff: 'system-ui,-apple-system,sans-serif',
}

/** Card theme presets for ProductPage feature cards (index 0–3). */
export const productCardThemes = [
  {
    bg: mkt.muted,
    orb1: 'transparent',
    orb2: 'transparent',
    orb1Pos: '8% 12%',
    orb2Pos: '88% 88%',
    accent: mkt.primary,
    accentDim: mkt.primaryDim,
    accentBorder: mkt.primaryBorder,
    gradientFrom: mkt.primary,
    gradientTo: mkt.primaryHover,
    checkRing: mkt.primaryRing,
    checkColor: mkt.primary,
    frameBg: mkt.frameBg,
    frameBorder: mkt.frameBorder,
    frameGlowColor: mkt.primaryDim,
    fadeColor: mkt.primaryTint,
    titleColor: mkt.titleColor,
    descColor: mkt.descColor,
    benefitColor: mkt.benefitColor,
    cardShadow:
      '0 2px 8px color-mix(in oklch, var(--foreground) 5%, transparent), 0 12px 40px color-mix(in oklch, var(--primary) 8%, transparent)',
    floatChipBg: mkt.floatChipBg,
    floatChipBorder: mkt.floatChipBorder,
    floatChipText: mkt.floatChipText,
    floatChip1: { label: 'Entries saved', value: '−60%', color: mkt.success },
    floatChip2: { label: 'Accuracy', value: '99.9%', color: mkt.info },
  },
  {
    bg: mkt.muted,
    orb1: 'transparent',
    orb2: 'transparent',
    orb1Pos: '12% 15%',
    orb2Pos: '90% 78%',
    accent: mkt.primary,
    accentDim: mkt.primaryDim,
    accentBorder: mkt.primaryBorder,
    gradientFrom: mkt.primary,
    gradientTo: mkt.primaryHover,
    checkRing: mkt.primaryRing,
    checkColor: mkt.primary,
    frameBg: mkt.frameBg,
    frameBorder: mkt.frameBorder,
    frameGlowColor:
      'color-mix(in oklch, var(--illustration-success) 9%, transparent)',
    fadeColor: mkt.successTint,
    titleColor: mkt.titleColor,
    descColor: mkt.descColor,
    benefitColor: mkt.benefitColor,
    cardShadow:
      '0 2px 8px color-mix(in oklch, var(--foreground) 5%, transparent), 0 12px 40px color-mix(in oklch, var(--illustration-success) 7%, transparent)',
    floatChipBg: mkt.floatChipBg,
    floatChipBorder: mkt.floatChipBorder,
    floatChipText: mkt.floatChipText,
    floatChip1: { label: 'Tasks automated', value: '+3×', color: mkt.success },
    floatChip2: { label: 'Time saved', value: '40h/mo', color: mkt.info },
  },
  {
    bg: mkt.muted,
    orb1: 'transparent',
    orb2: 'transparent',
    orb1Pos: '10% 16%',
    orb2Pos: '85% 82%',
    accent: mkt.primary,
    accentDim: mkt.primaryDim,
    accentBorder: mkt.primaryBorder,
    gradientFrom: mkt.primary,
    gradientTo: mkt.primaryHover,
    checkRing: mkt.primaryRing,
    checkColor: mkt.primary,
    frameBg: mkt.frameBg,
    frameBorder: mkt.frameBorder,
    frameGlowColor:
      'color-mix(in oklch, var(--illustration-warning) 8%, transparent)',
    fadeColor:
      'color-mix(in oklch, var(--illustration-warning) 6%, var(--background))',
    titleColor: mkt.titleColor,
    descColor: mkt.descColor,
    benefitColor: mkt.benefitColor,
    cardShadow:
      '0 2px 8px color-mix(in oklch, var(--foreground) 5%, transparent), 0 12px 40px color-mix(in oklch, var(--illustration-warning) 7%, transparent)',
    floatChipBg: mkt.floatChipBg,
    floatChipBorder: mkt.floatChipBorder,
    floatChipText: mkt.floatChipText,
    floatChip1: { label: 'Faster reports', value: '5×', color: mkt.warning },
    floatChip2: { label: 'Data sources', value: '50+', color: mkt.warning },
  },
  {
    bg: mkt.muted,
    orb1: 'transparent',
    orb2: 'transparent',
    orb1Pos: '7% 18%',
    orb2Pos: '92% 80%',
    accent: mkt.primary,
    accentDim: mkt.primaryDim,
    accentBorder: mkt.primaryBorder,
    gradientFrom: mkt.primary,
    gradientTo: mkt.primaryHover,
    checkRing: mkt.primaryRing,
    checkColor: mkt.primary,
    frameBg: mkt.frameBg,
    frameBorder: mkt.frameBorder,
    frameGlowColor: 'color-mix(in oklch, var(--chart-4) 9%, transparent)',
    fadeColor: 'color-mix(in oklch, var(--chart-4) 6%, var(--background))',
    titleColor: mkt.titleColor,
    descColor: mkt.descColor,
    benefitColor: mkt.benefitColor,
    cardShadow:
      '0 2px 8px color-mix(in oklch, var(--foreground) 5%, transparent), 0 12px 40px color-mix(in oklch, var(--chart-4) 7%, transparent)',
    floatChipBg: mkt.floatChipBg,
    floatChipBorder: mkt.floatChipBorder,
    floatChipText: mkt.floatChipText,
    floatChip1: { label: 'Compliance', value: '100%', color: 'var(--chart-4)' },
    floatChip2: { label: 'Audit trail', value: 'Live', color: mkt.destructive },
  },
] as const

/** FAMobileProductPage design tokens. */
export const faMobileTokens = {
  bg: mkt.background,
  bgSoft: mkt.panel,
  white: mkt.background,
  ink: mkt.ink,
  inkSoft: mkt.inkSoft,
  muted: mkt.mutedForeground,
  line: mkt.line,
  green: mkt.success,
  greenLite: mkt.successLight,
  blue: mkt.info,
  red: mkt.destructive,
} as const
